name: TornadoChest
version: 07.05.2020
main: com.infumia.t3sl4.sandikspawner.SandikSpawner
authors: [SYN_T3SL4]
depend:
  - Vault

commands:
  sandiksp:
    aliases:
      - chestsp
      - chestspawner
      - tornadochest
      - tornadochestsp
