name: TornadoChest
version: 27.04.2020
main: com.infumia.com.infumia.t3sl4.sandikspawner.SandikSpawner
authors: [SYN_T3SL4]
depend:
  - Vault

commands:
  tornadochestsp:
    aliases:
      - sandiksp
      - chestsp
      - chestspawner
      - tornadochest
# Yetkiler:
# tornadochestsp.dagit >> Spawner Dağıtma Komutunu Kullanmanızı Sağlar.
# tornadochestsp.ver >> Spawner Verme Komutunu Kullanmanızı Sağlar.
# tornadochestsp.ayarlar >> Ayarlar Komutunu Kullanmanızı Sağlar.
# tornadochestsp.reload >> Eklentiyi Yenilemenizi Sağlar.